import { readFileSync, writeFileSync, readdirSync, existsSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { execFileSync } from "node:child_process";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const lock = JSON.parse(readFileSync(join(root, "package-lock.json"), "utf8"));
const packages = [];
const overrides = JSON.parse(readFileSync(join(root, "third-party/license-overrides.json"), "utf8"));
const missing = [];
const skipped = new Set(["node_modules", ".git", "target", "tests", "test", "examples"]);
const licenseName = /^(licen[cs]e|copying|notice|copyright|unlicense|ofl)([._-]|$)/i;

function licenseFiles(directory, depth = 0) {
  const result = [];
  for (const item of readdirSync(directory, { withFileTypes: true })) {
    const path = join(directory, item.name);
    if (item.isFile() && licenseName.test(item.name)) result.push(path);
    if (item.isDirectory() && depth < 4 && !skipped.has(item.name)) {
      result.push(...licenseFiles(path, depth + 1));
    }
  }
  return result.sort();
}

function add(ecosystem, name, version, directory, license, extraFile) {
  const files = licenseFiles(directory);
  const override = overrides[ecosystem + ":" + name + "@" + version];
  for (const file of override?.files ?? []) {
    const path = join(root, file);
    if (!existsSync(path)) throw new Error("Missing reviewed license source: " + file);
    if (!files.includes(path)) files.push(path);
  }
  if (extraFile) {
    const file = resolve(directory, extraFile);
    if (existsSync(file) && !files.includes(file)) files.push(file);
  }
  if (!license && !extraFile || files.length === 0) {
    missing.push(ecosystem + ":" + name + "@" + version);
    return;
  }
  packages.push({
    ecosystem, name, version, note: override?.reason, license: license || "See included license file",
    texts: files.sort().map(file => ({
      name: file.startsWith(directory) ? relative(directory, file).replaceAll("\\", "/") : file.split(/[\\/]/).pop(),
      text: readFileSync(file, "utf8").replaceAll("\r\n", "\n").trim(),
    })),
  });
}

for (const [path, info] of Object.entries(lock.packages)) {
  if (!path) continue;
  const directory = join(root, path);
  const manifest = join(directory, "package.json");
  if (!existsSync(manifest)) {
    if (info.optional) continue; // Packages for other platforms are not installed.
    throw new Error("Run npm ci first; missing " + path);
  }
  const pkg = JSON.parse(readFileSync(manifest, "utf8"));
  add("npm", pkg.name, pkg.version, directory, pkg.license);
}

const metadata = JSON.parse(execFileSync("cargo", [
  "metadata", "--manifest-path", "src-tauri/Cargo.toml", "--locked",
  "--format-version", "1", "--filter-platform", "x86_64-pc-windows-msvc",
], { cwd: root, encoding: "utf8", maxBuffer: 32 * 1024 * 1024 }));
const resolved = new Set(metadata.resolve.nodes.map(node => node.id));
for (const pkg of metadata.packages) {
  if (!pkg.source || !resolved.has(pkg.id)) continue;
  add("Cargo", pkg.name, pkg.version, dirname(pkg.manifest_path), pkg.license, pkg.license_file);
}
if (missing.length) {
  throw new Error("Review missing license declarations/texts:\n" + missing.join("\n"));
}

packages.sort((a, b) => (a.ecosystem + ":" + a.name + "@" + a.version)
  .localeCompare(b.ecosystem + ":" + b.name + "@" + b.version, "en"));
const lines = [
  "Read Atlas — Third-party dependency notices",
  "Generated by npm run notices from installed npm packages and the Windows Cargo graph.",
  "Includes development/build dependencies conservatively. Platform-specific optional npm",
  "packages not installed on this machine are omitted. Original rights remain unchanged.",
  "See THIRD_PARTY_NOTICES.md and LICENSE for scope.",
  "",
];
for (const pkg of packages) {
  lines.push("=".repeat(78), pkg.ecosystem + ": " + pkg.name + "@" + pkg.version,
    "Declared license: " + pkg.license, "");
  if (pkg.note) lines.push("Source note: " + pkg.note, "");
  for (const item of pkg.texts) lines.push("--- " + item.name + " ---", item.text, "");
}
writeFileSync(join(root, "THIRD_PARTY_NOTICES.txt"), lines.join("\n"), "utf8");
console.log("Wrote notices for " + packages.length + " dependencies.");
